### ISSUE TITLE
Chunked transfer encoding

### ISSUE THREAD

**Issue by denneulin** [awslabs/aws-serverless-express#10]
Hi,

I use an express middleware that set to `chunked` the `transfer-encoding` headers 

``` javascript
'transfer-encoding': 'chunked'
```

In that case, I get the following error :

> The request could not be satisfied.
> CloudFront attempted to establish a connection with the origin, but either the attempt failed or the origin closed the connection.

To make my request works, in the `forwardResponseToApiGateway` function of the `aws-serverless-express/index.js` file I remove this header.

Do you think you could make chunked transfert encoding pass ?

**Comment by brettstack** [comment]
Chunked transfer is something we are looking into; unfortunately, for now
you will need to disable it.

**Comment by denneulin** [comment]
That's rally annoying but thanks for your answer ;)

**Comment by goldenbearkin** [comment]
Why is this closed? Is it solved?

**Comment by brettstack** [comment]
This is a limitation with API Gateway, and not the library. However, I will reopen this issue for tracking and notification purposes.

**Comment by goldenbearkin** [comment]
Thanks brettstack.
for those seeking a temporary solution mentioned by @denneulin above. Add 'delete headers' as below in the forwardResponseToApiGateway function.

````javascript
delete headers["transfer-encoding"]
const successResponse = {statusCode, body, headers}
````

**Comment by abhigna** [comment]
This should be working now. You don't need to explicitly remove the  `'transfer-encoding'` header anymore.

**Comment by ckuijjer** [comment]
@abhigna I think the `transfer-encoding: chunked` issue still exists. I've tried to use `aws-serverless-express` with `graphql-server-express` today and I run into the same issue as @denneulin

**Comment by brettstack** [comment]
Chunked encoding still isn't working, but we are now deleting the header for you https://github.com/awslabs/aws-serverless-express/commit/4d54a81b831eca97524f15b72fa8be379c80aedb#diff-168726dbe96b3ce427e7fedce31bb0bcR54
